# general settings
name: Swin2_mose
model_type: RealESRNetModel
scale: 3
num_gpu: auto # auto: can infer from your visible devices automatically. official: 4 GPUs
manual_seed: 0

# ----------------- options for synthesizing training data in RealESRNetModel ----------------- #
gt_usm: True # USM the ground-truth
high_order_degradation: False

# the first degradation process
resize_prob: [0.2, 0.7, 0.1] # up, down, keep
resize_range: [0.15, 1.5]
gaussian_noise_prob: 0.5
noise_range: [1, 30]
poisson_scale_range: [0.05, 3]
gray_noise_prob: 0.4
jpeg_range: [30, 95]

# the second degradation process
second_blur_prob: 0.8
resize_prob2: [0.3, 0.4, 0.3] # up, down, keep
resize_range2: [0.3, 1.2]
gaussian_noise_prob2: 0.5
noise_range2: [1, 25]
poisson_scale_range2: [0.05, 2.5]
gray_noise_prob2: 0.4
jpeg_range2: [30, 95]

gt_size: 192
lq_size: 64
queue_size: 180

# dataset and data loader settings
datasets:
  train:
    name: SRTrain
    type: PairedImageDataset
    dataroot_gt: data/train/HR
    dataroot_lq: data/train/LR
    meta_info: data/meta_info/meta_info_train.txt
    io_backend:
      type: disk
    gt_size: 192
    use_hflip: True
    use_rot: True

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 1
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: SRVal
    type: PairedImageDataset
    dataroot_gt: data/val/HR
    dataroot_lq: data/val/LR
    meta_info: data/meta_info/meta_info_val.txt
    io_backend:
      type: disk
    gt_size: 192
    use_hflip: False
    use_rot: False
    use_shuffle: False
    num_worker_per_gpu: 1
    batch_size_per_gpu: 4

# network structures
network_g:
  type: Swin2MoSE
  in_chans: 4
  embed_dim: 96
  depths: [6, 6, 6, 6]
  num_heads: [6, 6, 6, 6]
  window_size: 8
  mlp_ratio: 4
  qkv_bias: true
  drop_path_rate: 0.2
  patch_norm: true
  upscale: 3
  img_range: 1.0
  upsampler: pixelshuffle
  resi_connection: 1conv
  # type: HAT
  # in_chans: 4
  # embed_dim: 96
  # depths: [6, 6, 6, 6]
  # num_heads: [6, 6, 6, 6]
  # window_size: 8
  # mlp_ratio: 4
  # qkv_bias: true
  # drop_path_rate: 0.2
  # patch_norm: true
  # upscale: 3
  # img_range: 1.0
  # upsampler: pixelshuffle
  # resi_connection: 1conv
  # type: RRDBNet
  # num_in_ch: 4
  # num_out_ch: 4
  # num_feat: 64
  # num_block: 23
  # num_grow_ch: 32
  # scale: 3
  # type: SwinIR
  # in_chans: 4
  # embed_dim: 96
  # depths: [6, 6, 6, 6]
  # num_heads: [6, 6, 6, 6]
  # window_size: 8
  # mlp_ratio: 4.
  # qkv_bias: true
  # drop_path_rate: 0.1
  # upscale: 3
  # img_range: 1.0
  # upsampler: pixelshuffle
  # resi_connection: 1conv
  # type: EDSN #RRDBNet
  # num_in_ch: 4
  # num_out_ch: 4
  # num_feat: 64
  # num_block: 16 #23
  # # num_grow_ch: 32
  # scale: 3
  # type: RCAN
  # num_in_ch: 4
  # num_out_ch: 4
  # num_feat: 64
  # num_group: 10
  # num_block: 20
  # squeeze_factor: 16
  # upscale: 3
  # res_scale: 1
  # img_range: 1.
  # rgb_mean: [0.0, 0.0, 0.0, 0.0]

# path
path:
  pretrain_network_g: ~ #experiments/pretrained_models/ESRGAN_SRx4_DF2KOST_official-ff704c30.pth
  param_key_g: ~ #params_ema
  strict_load_g: ~ #true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 7e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [1000000]
    gamma: 0.5

  total_iter: 50000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: True

  metrics:
    psnr: # metric name
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  type: TensorboardLogger
  log_dir: experiments/RealESRGAN/tb_logger
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
